# Generated by Django 3.2.5 on 2022-04-26 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CBV', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cbv',
            name='image',
            field=models.ImageField(upload_to='cbv-images'),
        ),
    ]
