# Generated by Django 3.2.5 on 2022-04-26 06:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('CBV', '0002_alter_cbv_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(max_length=1000)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('image', models.ImageField(upload_to='post-images')),
            ],
        ),
        migrations.DeleteModel(
            name='cbv',
        ),
    ]
